name: Create Release on Merge to Master

on:
  push:
    branches:
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract commit message
        id: extract_commit_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.sha }})"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.extract_commit_message.outputs.message }}
          body: ${{ steps.extract_commit_message.outputs.message }}
          draft: false
          prerelease: false