name: Create Release on QA to Master Merge

on:
  pull_request:
    branches: 
      - main
    types:
      - closed

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract commit message
        id: extract_commit_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: ${{ steps.extract_commit_message.outputs.message }}
          body: ${{ steps.extract_commit_message.outputs.message }}
          draft: false
          prerelease: false
